### ISSUE TITLE
[BUG] Cannot Import Robustness Gym

### ISSUE THREAD

**Issue by Victor3011** [robustness-gym/robustness-gym#85]
**Describe the bug**
Importing robustness gym raises an import error

**To Reproduce**
Steps and code snippet that reproduce the behavior:

1. Install Robustness gym
`pip install robustnessgym`
2. Import Robustness gym
```python 
import robustnessgym as rb
```

Raises an import error
`/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/.local/lib/python3.8/site-packages/robustnessgym/__init__.py", line 17, in <module>
    from robustnessgym.core.model import HuggingfaceModel, LudwigModel, Model
  File "/home/<user>/.local/lib/python3.8/site-packages/robustnessgym/core/model.py", line 17, in <module>
    from robustnessgym.tasks.task import Task
  File "/home/<user>/.local/lib/python3.8/site-packages/robustnessgym/tasks/task.py", line 8, in <module>
    from robustnessgym.tasks.schema import Schema
  File "/home/<user>/.local/lib/python3.8/site-packages/robustnessgym/tasks/schema.py", line 6, in <module>
    from datasets.features import FeatureType
ImportError: cannot import name 'FeatureType' from 'datasets.features' (/home/<user>/.local/lib/python3.8/site-packages/datasets/features/__init__.py)
`

**Expected behavior**

Run
`pip install robustnessgym`
```python 
import robustnessgym as rb
```
No Error

**System Information**
 - OS: Linux
 - `robustnessgym` (v0.1.3)

**Comment by kanak000** [comment]
yes same error, did you find any way to solve this?
